### ISSUE TITLE
TinyMCE Rails Update 5 > 6 makes asset compilation fail

### ISSUE THREAD

**Issue by ut** [a-thousand-channels/ORTE-backend#248]
With tinymce-rails > 6, assset compilation fails

```$ RAILS_ENV=staging rails assets:precompile --trace```

<pre>
** Execute assets:precompile
rails aborted!
Uglifier::Error: 
/home/x/.rvm/gems/ruby-2.7.6/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
/home/x/.rvm/gems/ruby-2.7.6/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
/home/x/.rvm/gems/ruby-2.7.6/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
/home/x/.rvm/gems/ruby-2.7.6/gems/sprockets-4.1.1/lib/sprockets/compressing.rb:84:in `block in js_compressor='
/home/x/.rvm/gems/ruby-2.7.6/gems/sprockets-4.1.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/x/.rvm/gems/ruby-2.7.6/gems/sprockets-4.1.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/x/.rvm/gems/ruby-2.7.6/gems/sprockets-4.1.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
</pre>

**Comment by ut** [comment]
Workaround: Fix version to 5
